jest.mock('vscode', () => ({ workspace: { workspaceFolders: [{ uri: { fsPath: process.cwd() } }], getConfiguration: () => ({ get: (_key: string, value: unknown) => value }), asRelativePath: (value: string) => value }, window: { createOutputChannel: () => ({ appendLine: () => undefined, append: () => undefined, clear: () => undefined, show: () => undefined, hide: () => undefined, dispose: () => undefined }) }, Uri: { file: (fsPath: string) => ({ fsPath }), joinPath: (...parts: any[]) => ({ fsPath: parts.map((part) => part?.fsPath || String(part)).join('/') }) }, commands: { executeCommand: async () => undefined }, env: { clipboard: { readText: async () => '' } } }), { virtual: true });
import { OpenCodeClient } from '../../OpenCodeClient';
import { loadAppendSuccessorProtocolHarness } from '../helpers/append-successor-protocol-harness';
const clients: OpenCodeClient[] = [];
afterEach(async () => { await Promise.all(clients.splice(0).map((client) => client.dispose())); });
describe('append successor canonical presentation protocol', () => {
    const makeClient = () => { const client: any = new OpenCodeClient(); clients.push(client); client.startTurn('ses_f8', 'local-root'); client.setCurrentTurnUserMsgId('ses_f8', 'msg_root', 'test'); client.displayTurnUserMsgIdBySession.set('ses_f8', 'msg_root'); client.beginAppendPrompt('ses_f8', 'append-client', 'queued append', 'msg_root'); client.bindAppendUserMessage('ses_f8', 'msg_append'); client.finishTurn('ses_f8'); return client; };
    it('binds an explicitly parented post-final successor exactly once', () => { const client = makeClient(); const event = { info: { id: 'msg_successor', sessionID: 'ses_f8', role: 'assistant', parentID: 'msg_append' } }; expect(client.mapServerEventToChatEvents('message.updated', event, 'sse')).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'turnInFlight', ownerMsgId: 'msg_successor' })])); expect(client.mapServerEventToChatEvents('message.updated', event, 'sse')).not.toEqual(expect.arrayContaining([expect.objectContaining({ type: 'turnInFlight' })])); });
    it('emits exactly one aborted successor marker and keeps user cancellation silent', () => { const client = makeClient(); client.mapServerEventToChatEvents('message.updated', { info: { id: 'msg_successor', sessionID: 'ses_f8', role: 'assistant', parentID: 'msg_append' } }, 'sse'); expect(client.mapServerEventToChatEvents('session.error', { sessionID: 'ses_f8', error: { name: 'MessageAbortedError', message: 'aborted' } }, 'sse')).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'error', appendSuccessorOutcome: 'aborted' })])); client.canceledActiveTurnBySession.set('ses_f8', true); expect(client.mapServerEventToChatEvents('session.error', { sessionID: 'ses_f8', error: { name: 'MessageAbortedError' } }, 'sse').some((event: any) => event.type === 'error')).toBe(false); });
    it('does not rekey an acknowledged append user into its successor assistant', () => { const { context, sessions } = loadAppendSuccessorProtocolHarness(); const session: any = { messagesById: new Map([['msg_append', { id: 'msg_append', role: 'user', text: 'queued' }]]), timeline: ['msg_append'], segmentsByNoticeKey: new Map(), clientKeyToServerId: new Map(), serverIdToClientKey: new Map(), appendComposerDrafts: new Map(), currentTurnAssistantKey: 'msg_append', currentTurnAssistantMsgId: 'msg_append', thinkingId: 'msg_append' }; sessions.set('ses_f8', session); context.replaceKeyEverywhere('msg_append', 'msg_successor', 'ses_f8'); expect(session.messagesById.get('msg_append').role).toBe('user'); expect(session.messagesById.has('msg_successor')).toBe(false); });
    it('keeps ordinary transitions callable through the neutral extraction', () => { const { context, sessions } = loadAppendSuccessorProtocolHarness(); sessions.set('ses_f8', { messagesById: new Map([['msg_assistant', { id: 'msg_assistant', meta: {} }]]), currentTurnAssistantKey: null, thinkingId: null }); Object.assign(context, { getEventSessionId: () => 'ses_f8', updateSendGate: () => undefined, maybeExitAppendInputModeAfterTurnEnd: () => undefined }); expect(context.applyAppendSuccessorProtocolTransition({ type: 'turnInFlight', inFlight: true, ownerMsgId: 'msg_assistant' })).toBe(true); });
});
