jest.mock('vscode', () => ({ workspace: { workspaceFolders: [{ uri: { fsPath: process.cwd() } }], getConfiguration: () => ({ get: (_key: string, value: unknown) => value }), asRelativePath: (value: string) => value }, window: { createOutputChannel: () => ({ appendLine: () => undefined, append: () => undefined, clear: () => undefined, show: () => undefined, hide: () => undefined, dispose: () => undefined }) }, Uri: { file: (fsPath: string) => ({ fsPath }), joinPath: (...parts: any[]) => ({ fsPath: parts.map((part) => part?.fsPath || String(part)).join('/') }) }, commands: { executeCommand: async () => undefined }, env: { clipboard: { readText: async () => '' } } }), { virtual: true });
import { OpenCodeClient } from '../../OpenCodeClient';
import { inspectAppendSuccessorDispatcherScope, reconstructDefectiveHelperRed } from '../helpers/append-successor-protocol-harness';

const clients: OpenCodeClient[] = [];
afterEach(async () => { await Promise.all(clients.splice(0).map((client) => client.dispose())); });

describe('append successor canonical presentation protocol', () => {
    const makeClient = () => { const client: any = new OpenCodeClient(); clients.push(client); client.startTurn('ses_f8', 'local-root'); client.setCurrentTurnUserMsgId('ses_f8', 'msg_root', 'test'); client.displayTurnUserMsgIdBySession.set('ses_f8', 'msg_root'); client.beginAppendPrompt('ses_f8', 'append-client', 'queued append', 'msg_root'); client.bindAppendUserMessage('ses_f8', 'msg_append'); client.finishTurn('ses_f8'); return client; };
    it('binds an explicitly parented post-final successor exactly once', () => { const client = makeClient(); const event = { info: { id: 'msg_successor', sessionID: 'ses_f8', role: 'assistant', parentID: 'msg_append' } }; expect(client.mapServerEventToChatEvents('message.updated', event, 'sse')).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'turnInFlight', ownerMsgId: 'msg_successor' })])); expect(client.mapServerEventToChatEvents('message.updated', event, 'sse')).not.toEqual(expect.arrayContaining([expect.objectContaining({ type: 'turnInFlight' })])); });
    it('emits exactly one real-abort marker and keeps user cancellation silent', () => { const client = makeClient(); client.mapServerEventToChatEvents('message.updated', { info: { id: 'msg_successor', sessionID: 'ses_f8', role: 'assistant', parentID: 'msg_append' } }, 'sse'); expect(client.mapServerEventToChatEvents('session.error', { sessionID: 'ses_f8', error: { name: 'MessageAbortedError', message: 'aborted' } }, 'sse')).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'error', appendSuccessorOutcome: 'aborted' })])); client.canceledActiveTurnBySession.set('ses_f8', true); expect(client.mapServerEventToChatEvents('session.error', { sessionID: 'ses_f8', error: { name: 'MessageAbortedError' } }, 'sse').some((event: any) => event.type === 'error')).toBe(false); });
    it('reconstructs the reviewed defective helper RED outside its closure', () => { const red = reconstructDefectiveHelperRed(); expect(red.assistantMessageMetaError).toBe('handleAssistantMeta is not defined'); expect(red.turnInFlightError).toBe('maybeExitAppendInputModeAfterTurnEnd is not defined'); expect(red.start).toBeLessThan(red.domStart); expect(red.end).toBeLessThan(red.dispatcherStart); });
    it('keeps the two case bodies in the DOMContentLoaded dispatcher and removes the defective helper', () => { const check = inspectAppendSuccessorDispatcherScope(); expect(check.source).not.toContain('applyAppendSuccessorProtocolTransition'); expect(check.domStart).toBeGreaterThanOrEqual(0); expect(check.dispatcherStart).toBeGreaterThan(check.domStart); expect(check.turnCase).toBeGreaterThan(check.dispatcherStart); expect(check.metaCase).toBeGreaterThan(check.turnCase); expect(check.domEnd).toBeGreaterThan(check.metaCase); expect(check.source).toContain("payload: ['reject.user->assistant-role'"); });
});
